CREATE DATABASE ECommerceImovel
GO

USE ECommerceImovel
GO

CREATE TABLE Tipo
(
TipoId INT IDENTITY(1,1),
Tipo VARCHAR(250),
CONSTRAINT PK_Tipo PRIMARY KEY (TipoId)
)
GO

CREATE TABLE Usuario
(
UsuarioId INT IDENTITY(1,1),
Nome VARCHAR NOT NULL,
Telefone VARCHAR NOT NULL,
Email NVARCHAR UNIQUE,
Senha VARBINARY NOT NULL,
FotoURL			NVARCHAR(500) NULL,
CriadoEM		DATETIME2(0) NOT NULL DEFAULT DATEADD(sysutcdatetime())
CONSTRAINT Pk_Usuario PRIMARY KEY (UsuarioId)
